# MySQL 配置
[mysql]
host = localhost
user = root
password = 12345678
database = subjects_kg

# Redis 配置
[redis]
host = localhost
port = 6380
password = 1234
db = 0

# Milvus 配置
[milvus]
host = localhost
port = 19530
database_name = itcast
collection_name = edurag_0706

# LLM 配置
[llm]
model = qwen3-max
dashscope_api_key = sk-98dd86b65cc549538543a08ed0691508
dashscope_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1

# 检索参数配置
[retrieval]
parent_chunk_size = 1200
child_chunk_size = 300
chunk_overlap = 50
retrieval_k = 5
candidate_m = 5

# 日志配置
[logger]
log_file = G:\code\python\Python-Learn\Project\Itcast_qa_system\logs\app.log

# 应用配置
[app]
valid_sources = ["ai", "java", "test", "ops", "bigdata"]
customer_service_phone = 12345678