version: '3.8'

services:
  # 主应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itcast_app
    ports:
      - "8003:8003"
    volumes:
      - ./docker_logs:/app/logs
      - ./rag_qa/models:/Project/Itcast_qa_system/rag_qa/models
#      - ./rag_qa/data:/app/rag_qa/data
#      - ./mysql_qa/data:/app/mysql_qa/data
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=sk-1c419112af98425885f4d440b79d192e
    networks:
      - itcast_network
    restart: unless-stopped

networks:
  itcast_network:
    external: true